name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    env:
      PROJECT: Then.xcodeproj
      SCHEME: Then-Package
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

          - sdk: macosx
            destination: arch=x86_64

          - sdk: appletvsimulator
            destination: platform=tvOS Simulator,name=Apple TV,OS=latest

    steps:
    - uses: actions/checkout@v1

    - name: List SDKs and Devices
      run: xcodebuild -showsdks; instruments -s

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
